### ISSUE TITLE
Feature Request: Support control characters in "format" of the options.

### ISSUE THREAD

**Issue by juyamagu** [zaki-yama/copy-title-and-url-as-markdown#8] opened 2019-07-11 01:20 UTC
Thank you for your great extension, helping me a lots.
I would like to request a new feature with great respect for you.

With the following setting, the current behavior is as "Now", but "Expect" would be expected.

![image](https://user-images.githubusercontent.com/52237425/61014971-da20a200-a3c4-11e9-893a-a32914fb674f.png)

Now:
```
Google\nhttps://www.google.com/
```

Expect:
```
Google
https://www.google.com/
```

**Comment by zaki-yama** [comment] 2019-07-11 06:08
@juyamagu 
Thank you for your feedback!!
I'll try when I have time.

**Comment by zaki-yama** [comment] 2019-07-11 06:45
Duplicate of #6

**Comment by zaki-yama** [comment] 2019-07-11 18:50
@juyamagu 
I updated the extension, now you can add line breaks in option page.
Please try it.

**Comment by juyamagu** [comment] 2019-07-12 00:30
I am sorry for my lack of checking the duplicate issue, and have to say my appreciation about your rapid response. Thanks a lot!

**Closed** 2019-07-12 03:38 UTC
